#pragma once

enum class INPUT_EVENT
{
	INPUT_EVENT_LEFT_STICK_UP = 0,
	INPUT_EVENT_LEFT_STICK_DOWN,
	INPUT_EVENT_LEFT_STICK_RIGHT,
	INPUT_EVENT_LEFT_STICK_LEFT,
	INPUT_EVENT_RIGHT_STICK_UP,
	INPUT_EVENT_RIGHT_STICK_DOWN,
	INPUT_EVENT_RIGHT_STICK_RIGHT,
	INPUT_EVENT_RIGHT_STICK_LEFT,
	INPUT_EVENT_FULL_STOP,
	INPUT_EVENT_COUNT = INPUT_EVENT_FULL_STOP,
};
